"""Tenant scoping for the Craft ORM.

The tenant is bound to a database *session variable*, which row-level security
policies read. That is what makes isolation something the application cannot
forget: a query with no tenant bound returns nothing because the policy's
predicate is NULL, not because a Python `where` clause happened to be appended.

The previous model — one PostgreSQL schema per tenant, selected with
`SET search_path` — is still available through `DB.set_tenant_schema()` and is
the right answer for the handful of tenants that need physical separation. It
is no longer the default, because it migrates every tenant separately, does DDL
on the request path for each new one, and multiplies the system catalogue by
the tenant count.

Category: Core Framework (ORM).
Relations:
  - Bound as `tenant`, exposed via the `Tenant` facade.
  - `ScopeTenant` (`engine/http/middleware.py`) binds it per request;
    `QueueManager.work()` binds it per job from the job's stored `tenant_id`.
  - Policies are generated by `Blueprint.tenant_scoped()`
    (`engine/migrations/schema.py`) and audited by `dev.py db:audit-rls`.
References:
  - Guide: `documentation/orm.md#multi-tenancy`
"""
# Craft Framework
# Copyright (c) 2026 Antonio Santos <snarthost@gmail.com>
# Licensed under the MIT License. See LICENSE in the project root.

from __future__ import annotations

import contextlib
from contextvars import ContextVar
from typing import Any, Iterator, List, Optional

#: Per-request / per-task, never process-wide.
#:
#: A `ContextVar` rather than a `threading.local`: the HTTP kernel serves each
#: request with `run_in_threadpool`, which copies the caller's context into the
#: worker thread and discards mutations on the way back out. That gives request
#: isolation for free, and the same object keeps working unchanged if any part
#: of the framework ever runs natively async.
_current: ContextVar[Optional[str]] = ContextVar("craft_tenant", default=None)


def current_tenant_id() -> Optional[str]:
    """The tenant bound in this context, or None. Safe to import anywhere."""
    return _current.get()


class TenantNotBoundError(RuntimeError):
    """A tenant-scoped operation ran with no tenant in context."""


class TenantIsolationError(RuntimeError):
    """The policies exist but cannot apply to the connecting role."""


class TenantManager:
    """Binds the current tenant to the connection's session variable."""

    def __init__(self, app: Any = None) -> None:
        self.app = app

    @property
    def db(self) -> Any:
        if self.app is not None:
            return self.app.make("db")
        from engine.container.application import Container

        return Container.getInstance().make("db")

    @property
    def guc(self) -> str:
        from engine.orm.connection import Connection

        return Connection.TENANT_GUC

    # -- reading ---------------------------------------------------------------

    def id(self) -> Optional[str]:
        return _current.get()

    def id_or_fail(self) -> str:
        """The bound tenant, or a refusal that names the fix.

        Raising beats returning None: a tenant-scoped query built with no
        tenant would otherwise compile to `tenant_id = NULL`, match nothing, and
        look exactly like a customer with no data.
        """
        value = _current.get()
        if not value:
            raise TenantNotBoundError(
                "No tenant is bound. Wrap the work in `Tenant.scope(tenant_id)`, "
                "or serve the request through the ScopeTenant middleware."
            )
        return str(value)

    def check(self) -> Optional[str]:
        """What the *database* thinks the tenant is — for tests and diagnosis.

        Reading it back rather than trusting the Python side is the only way to
        catch a pooled connection that kept a previous borrower's value.
        """
        if not self.db.dialect.supports("rls"):
            return None
        row = self.db.statement(
            "SELECT NULLIF(current_setting(?, true), '') AS tenant", [self.guc], read=True
        ).fetchone()
        return row["tenant"] if row is not None else None

    # -- binding ---------------------------------------------------------------

    def bind(self, tenant_id: Optional[str], *, local: bool = False) -> None:
        """Bind `tenant_id` for this context and push it to the connection.

        `local=False` (the default for a request) sets a session variable and
        relies on `Connection.release()` to clear it at checkin — the contract
        `search_path` already has. `local=True` scopes the setting to the open
        transaction, which the database unwinds itself; use it in queue workers
        and anywhere there is no checkin to hang the reset on.
        """
        _current.set(str(tenant_id) if tenant_id else None)
        if not self.db.dialect.supports("rls"):
            # Development and the test-suite. The `TenantScoped` mixin still
            # scopes queries in Python, so a cross-tenant assertion fails here
            # too instead of quietly passing.
            return
        self.db.write_connection.use_tenant(tenant_id, local=local)
        read = getattr(self.db, "_read", None)
        if read is not None:
            read.use_tenant(tenant_id, local=local)

    @contextlib.contextmanager
    def scope(self, tenant_id: Optional[str], *, local: bool = False) -> Iterator[None]:
        """Run a block as one tenant, restoring the previous one afterwards.

            with Tenant.scope(invoice.tenant_id):
                Invoice.query().get()

        Restoring rather than clearing matters for nested use: an admin task
        iterating tenants must come back out on the tenant it started on, not on
        none — which would make the next query outside the block return nothing.
        """
        token = _current.set(str(tenant_id) if tenant_id else None)
        try:
            self.bind(tenant_id, local=local)
            yield
        finally:
            _current.reset(token)
            self.bind(_current.get(), local=local)

    def clear(self) -> None:
        """Unbind the tenant. Every scoped query then matches nothing."""
        self.bind(None)

    # -- enforcement -----------------------------------------------------------

    #: Answered once per process. The role a connection authenticates as does
    #: not change under it, and this is a catalogue query on the request path.
    _enforcement: Optional[dict] = None

    def enforcement(self, refresh: bool = False) -> dict:
        """Whether the connecting role is actually subject to policies.

        Row-level security does not apply to a **superuser**, and does not apply
        to a role with **BYPASSRLS**. Neither is affected by
        `FORCE ROW LEVEL SECURITY`, which only reaches the table's owner. So a
        table can report `relrowsecurity = true`, `relforcerowsecurity = true`
        and carry a correct policy, and still return every tenant's rows to
        everyone — which is precisely the failure this whole design exists to
        rule out, wearing the costume of a working one.

        The only way to know is to ask the catalogue.
        """
        if TenantManager._enforcement is not None and not refresh:
            return TenantManager._enforcement

        if not self.db.dialect.supports("rls"):
            result = {"role": None, "enforced": False, "reason": "no row-level security"}
        else:
            row = self.db.statement(
                "SELECT rolname, rolsuper, rolbypassrls FROM pg_roles "
                "WHERE rolname = current_user",
                read=True,
            ).fetchone()
            if row is None:
                result = {"role": None, "enforced": False, "reason": "unknown role"}
            elif row["rolsuper"]:
                result = {"role": row["rolname"], "enforced": False,
                          "reason": "the role is a superuser"}
            elif row["rolbypassrls"]:
                result = {"role": row["rolname"], "enforced": False,
                          "reason": "the role has BYPASSRLS"}
            else:
                result = {"role": row["rolname"], "enforced": True, "reason": None}

        TenantManager._enforcement = result
        return result

    def assert_enforced(self) -> None:
        """Refuse to serve tenant traffic that the database will not isolate."""
        status = self.enforcement()
        if status["enforced"]:
            return
        raise TenantIsolationError(
            f"Tenant isolation is not in force: {status['reason']} "
            f"(connected as {status['role']!r}), so every row-level security "
            f"policy on this database is inert and one tenant's query can read "
            f"another's rows. Connect the application as a role that is neither "
            f"a superuser nor granted BYPASSRLS, and does not own the tables."
        )

    # -- auditing --------------------------------------------------------------

    #: Tables that carry a `tenant_id` without being tenant-scoped, and must
    #: not be flagged by the audit.
    #:
    #: The queue is the case that matters. A job records the tenant it was
    #: dispatched under so the worker can rebind it before `handle()` runs —
    #: the column is a *carrier*, not a boundary. Putting an isolation policy
    #: on `jobs` would break the queue outright: a worker claims across all
    #: tenants and binds nothing until it has a job, so under a policy it would
    #: claim nothing and sit idle against a full queue.
    #:
    #: Extend it from config with `database.tenancy.unscoped_tables` for an
    #: application table in the same position.
    FRAMEWORK_UNSCOPED_TABLES = frozenset({"jobs", "failed_jobs"})

    def unscoped_tables(self) -> set:
        configured = ()
        try:
            configured = (
                self.app.make("config").get("database.tenancy.unscoped_tables") or ()
            )
        except Exception:
            configured = ()
        return set(self.FRAMEWORK_UNSCOPED_TABLES) | set(configured)

    def audit(self) -> List[dict]:
        """Tables carrying a `tenant_id` and the isolation they actually have.

        The realistic way this design decays is a table added without
        `t.tenant_scoped()`: nothing errors, nothing looks wrong, and one table
        serves every tenant's rows to everyone. `dev.py db:audit-rls` runs this
        and exits non-zero, so CI catches it instead of a customer.

        Tables in `unscoped_tables()` are reported but never counted as
        failures — see the note there for why the queue is one of them.
        """
        self.db.dialect.require("rls", "is what `db:audit-rls` inspects")
        rows = self.db.statement(
            """
            SELECT c.relname                AS table_name,
                   c.relrowsecurity         AS rls_enabled,
                   c.relforcerowsecurity    AS rls_forced,
                   (SELECT count(*) FROM pg_policy p WHERE p.polrelid = c.oid) AS policies
              FROM pg_class c
              JOIN pg_namespace n ON n.oid = c.relnamespace
             WHERE c.relkind IN ('r', 'p')
               AND n.nspname = current_schema()
               AND EXISTS (
                   SELECT 1 FROM pg_attribute a
                    WHERE a.attrelid = c.oid AND a.attname = 'tenant_id' AND a.attnum > 0
               )
             ORDER BY c.relname
            """,
            read=True,
        ).fetchall()

        exempt = self.unscoped_tables()
        report = []
        for row in rows:
            record = dict(row)
            record["exempt"] = record["table_name"] in exempt
            record["protected"] = record["exempt"] or bool(
                record["rls_enabled"] and record["rls_forced"] and record["policies"]
            )
            report.append(record)
        return report


__all__ = ["TenantManager", "TenantNotBoundError", "current_tenant_id"]
